using System;
using System.Collections.Generic;
using UnityEngine;
using bbpfer.FundamentalManagers;

namespace bbpfer.FundamentalManagers.ExternalLoaders
{
    public partial class TileTexturesLoaders
    {
        public static void Load()
        {
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "F3", "F4", "END" }, "OrangeBrickWall", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class }, Enums.TileTextures.Wall, 42);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "F3", "F4", "END" }, "OfficeOrangeBrickWall", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Wall, 52);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "END" }, "PinkWallBrick", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class }, Enums.TileTextures.Wall, 32);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "END" }, "OfficePinkWallBrick", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Wall, 44);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "END" }, "HappyWall", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Storage }, Enums.TileTextures.Wall, 53);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "END" }, "OfficeHappyWall", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Wall, 68);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "END" }, "NotFoundWall", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Storage }, Enums.TileTextures.Wall, 40);
            AssetsCreator.CreateTileTexture(new string[] { "F3", "F4", "END" }, "NotFoundWallBlack", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Storage }, Enums.TileTextures.Wall, 35);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "END" }, "OfficeNotFoundWall", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Faculty}, Enums.TileTextures.Wall, 35);
            AssetsCreator.CreateTileTexture(new string[] { "F3", "F4", "END" }, "OfficeNotFoundWallBlack", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Wall, 40);
            AssetsCreator.CreateTileTexture(new string[] { "F2", "END" }, "RerldAnimatedBrick 1", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Storage }, Enums.TileTextures.Wall, 35);
            AssetsCreator.CreateTileTexture(new string[] { "F3", "F4", "END" }, "RerldAnimatedBrick 2", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Storage }, Enums.TileTextures.Wall, 40);
            AssetsCreator.CreateTileTexture(new string[] { "F2", "F3", "F4", "END" }, "redBrick", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class }, Enums.TileTextures.Wall, 30);
            AssetsCreator.CreateTileTexture(new string[] { "F2", "F3", "F4", "END" }, "OfficeRedBrick", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Wall, 30);
            AssetsCreator.CreateTileTexture(new string[] { "F3", "F4", "END" }, "NotFoundWallBlack", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Storage }, Enums.TileTextures.Wall, 35);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "END" }, "FunWall", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Storage }, Enums.TileTextures.Wall, 32);
            AssetsCreator.CreateTileTexture(new string[] { "F3", "F4", "END" }, "UnfunWall", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Storage }, Enums.TileTextures.Wall, 32);
            AssetsCreator.CreateTileTexture(new string[] { "F3", "F4", "END" }, "SaloonWallWithMolding", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Faculty}, Enums.TileTextures.Wall, 40);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "END" }, "WlwightAnimatedBrick", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Storage }, Enums.TileTextures.Wall, 38);
            AssetsCreator.CreateTileTexture(new string[] { "F3", "F4", "END" }, "BalckAnimatedBrick", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class }, Enums.TileTextures.Wall, 32);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "F3", "F4", "END" }, "SaloonWall", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class }, Enums.TileTextures.Wall, 50);
            AssetsCreator.CreateTileTexture(new string[] { "F3", "F4", "END" }, "MetalWall", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class }, Enums.TileTextures.Wall, 30);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "END" }, "NotMorePurpleWall", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class }, Enums.TileTextures.Wall, 42);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "END" }, "FadeWall", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class }, Enums.TileTextures.Wall, 25);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "END" }, "ConcreteWall", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Storage }, Enums.TileTextures.Wall, 38);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "F3", "F3", "END" }, "CarpetWall", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class }, Enums.TileTextures.Wall, 45);
            AssetsCreator.CreateTileTexture(new string[] { "F3", "F4", "END" }, "BlackBrickWall", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class }, Enums.TileTextures.Wall, 35);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "END" }, "SaloonWallWhite", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class }, Enums.TileTextures.Wall, 40);
            AssetsCreator.CreateTileTexture(new string[] { "F3", "F4", "END" }, "SaloonWallDark", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class }, Enums.TileTextures.Wall, 48);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "END" }, "OfficeSaloonWallWhite", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Wall, 30);
            AssetsCreator.CreateTileTexture(new string[] { "F3", "F4", "END" }, "OfficeSaloonWallDark", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Wall, 38);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "END" }, "Win95RedBrick", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class }, Enums.TileTextures.Wall, 45);
            AssetsCreator.CreateTileTexture(new string[] { "F3", "F4", "END" }, "Win95Brick", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class }, Enums.TileTextures.Wall, 32);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "END" }, "OfficeWin95RedBrick", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Wall, 35);
            AssetsCreator.CreateTileTexture(new string[] { "F3", "F4", "END" }, "OfficeWin95Brick", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Wall, 50);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "F3", "F4", "END" }, "theifBrickWall", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Storage }, Enums.TileTextures.Wall, 44);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "F3", "F4", "END" }, "theifBrickWallFaculty", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Wall, 44);

            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "F3", "F4", "END" }, "Carpet_Red", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty, Enums.RoomGroupTextures.Storage }, Enums.TileTextures.Floor, 65);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "F3", "F4", "END" }, "Carpet_Gray", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty, Enums.RoomGroupTextures.Storage }, Enums.TileTextures.Floor, 60);
            AssetsCreator.CreateTileTexture(new string[] { "F2", "F3", "F4", "END" }, "Calpert_Green", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Floor, 47);
            AssetsCreator.CreateTileTexture(new string[] { "F2", "F3", "F4", "END" }, "Calpert_Olange", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Floor, 47);
            AssetsCreator.CreateTileTexture(new string[] { "F2", "F3", "F4", "END" }, "Calpert_Red", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty, Enums.RoomGroupTextures.Storage }, Enums.TileTextures.Floor, 47);
            AssetsCreator.CreateTileTexture(new string[] { "F2", "F3", "F4", "END" }, "Calpert_Gray", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty, Enums.RoomGroupTextures.Storage }, Enums.TileTextures.Floor, 47);
            AssetsCreator.CreateTileTexture(new string[] { "F2", "F3", "F4", "END" }, "Calpert", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Floor, 47);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "F3", "F4", "END" }, "tiledwood", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Floor, 35);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "END" }, "GenericWoodFloor", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Floor, 40);
            AssetsCreator.CreateTileTexture(new string[] { "F3", "F4", "END" }, "GenericWoodFloorDark", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Floor, 38);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "END" }, "GenericWoodFloor2_New", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Floor, 30);
            AssetsCreator.CreateTileTexture(new string[] { "F3", "F4", "END" }, "GenericWoodFloor2Dark_New", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Floor, 34);
            //AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "END" }, "WoodwoodFloorDk", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Floor, 35);
            //AssetsCreator.CreateTileTexture(new string[] { "F3", "F4", "END" }, "WoodwoodFloorDalrk", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Floor, 40);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "F3", "END" }, "NotFoundWoodFloor", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Floor, 45);
            AssetsCreator.CreateTileTexture(new string[] { "F3", "F4", "END" }, "GenericWoodFloor2Dark_New", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Floor, 42);
            AssetsCreator.CreateTileTexture(new string[] { "F2", "F1", "END" }, "NotFoundBirchWoodFloor", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Floor, 47);
            AssetsCreator.CreateTileTexture(new string[] { "F2", "F1", "F3", "F4", "END" }, "NotFoundWoodFloor", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Floor, 30);
            AssetsCreator.CreateTileTexture(new string[] { "F3", "F4", "END" }, "NotFoundDarkWoodFloor", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Floor, 52);
            AssetsCreator.CreateTileTexture(new string[] { "F2", "F1", "END" }, "AspargoFloor2", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Floor, 37);
            AssetsCreator.CreateTileTexture(new string[] { "F2", "F3", "F4", "END" }, "AspargoFloor", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Floor, 38);
            AssetsCreator.CreateTileTexture(new string[] { "F2", "F3", "F4", "END" }, "AspargoFloor3", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Floor, 30);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "F3", "F4", "END" }, "NotFoundCarpet", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Floor, 40);
            AssetsCreator.CreateTileTexture(new string[] { "F2", "F3", "F4", "END" }, "KitchenFloor", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Floor, 20);
            AssetsCreator.CreateTileTexture(new string[] { "F2", "F3", "F4", "END" }, "LiteryNotebookFloorMixed", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Floor, 48);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "F3", "F4", "END" }, "GenericDarkWood1", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Floor, 35);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "F3", "F4", "END" }, "BasicRealCarpet", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Floor, 30);
            AssetsCreator.CreateTileTexture(new string[] { "F2", "F3", "F4", "END" }, "WackyFloor", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall }, Enums.TileTextures.Floor, 32);
            AssetsCreator.CreateTileTexture(new string[] { "F3", "F4", "END" }, "DiamongPlateFloor", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall }, Enums.TileTextures.Floor, 25);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "END" }, "GenericWoodFloor", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Floor, 40);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "END" }, "PlankWood", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Floor, 40);

            AssetsCreator.CreateTileTexture(new string[] { "F2", "F3", "F4", "END" }, "FancyCeiling", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Ceiling, 35);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "F3", "F4", "END" }, "BasicRealCeiling", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty, Enums.RoomGroupTextures.Storage }, Enums.TileTextures.Ceiling, 24);
            AssetsCreator.CreateTileTexture(new string[] { "F2", "F3", "F4", "END" }, "CeilingPopNotCorn", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Ceiling, 28);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "F3", "F4", "END" }, "GenericCeiling1", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Ceiling, 40);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "F3", "F4", "END" }, "HapracoNewCeiling", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty, Enums.RoomGroupTextures.Storage }, Enums.TileTextures.Ceiling, 36);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "F3", "F4", "END" }, "NotFoundCeiling", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty }, Enums.TileTextures.Ceiling, 28);
            AssetsCreator.CreateTileTexture(new string[] { "F1", "F2", "F3", "F4", "END" }, "NyanCeiling", new Enums.RoomGroupTextures[] { Enums.RoomGroupTextures.Hall, Enums.RoomGroupTextures.Class, Enums.RoomGroupTextures.Faculty, Enums.RoomGroupTextures.Storage }, Enums.TileTextures.Ceiling, 32);
        }
    }
}
